export const plans = [
  "Warm-up for the athletes",
  "Opening Ceremony",
  "Teams' greeting parade",
  "Welcoming words of organizers and special guests",
  "Presentation video of the project",
  "Presentation video of the sponsors/partners",
  "Commentators Speech (live communication)",
  "Contest of predictions (for the victory)",
  "Semi-finals",
  "Professional male teams",
  "Professional female teams",
  "Amateur male teams",
  "Amateur female teams",
  "Junior teams",
  "Entertainment",
  "Lunchtime",
  "Ace Battle Universe Grand Presentation",
  "Sponsor/Partners Announcements",
  "Finals",
];
