export const countries = {
  Albania: "Albania",
  Andorra: "Andorra",
  Austria: "Austria",
  Belarus: "Belarus",
  Belgium: "Belgium",
  "Bosnia and Herzegovina": "Bosnia and Herzegovina",
  Bulgaria: "Bulgaria",
  Croatia: "Croatia",
  Cyprus: "Cyprus",
  "Czech Republic": "Czech Republic",
  Denmark: "Denmark",
  Estonia: "Estonia",
  Finland: "Finland",
  France: "France",
  Germany: "Germany",
  Greece: "Greece",
  Hungary: "Hungary",
  Iceland: "Iceland",
  Ireland: "Ireland",
  Italy: "Italy",
  Kosovo: "Kosovo",
  Latvia: "Latvia",
  Liechtenstein: "Liechtenstein",
  Lithuania: "Lithuania",
  Luxembourg: "Luxembourg",
  Malta: "Malta",
  Moldova: "Moldova",
  Monaco: "Monaco",
  Montenegro: "Montenegro",
  Netherlands: "Netherlands",
  "North Macedonia": "North Macedonia",
  Norway: "Norway",
  Poland: "Poland",
  Portugal: "Portugal",
  Romania: "Romania",
  Russia: "Russia",
  "San Marino": "San Marino",
  Serbia: "Serbia",
  Slovakia: "Slovakia",
  Slovenia: "Slovenia",
  Spain: "Spain",
  Sweden: "Sweden",
  Switzerland: "Switzerland",
  Ukraine: "Ukraine",
  "United Kingdom": "United Kingdom",
};

export const years = {
  "2020": "2020",
  "2021": "2021",
  "2022": "2022",
  "2023": "2023",
};

export const months = {
  January: "January",
  February: "February",
  March: "March",
  April: "April",
  May: "May",
  June: "June",
  July: "July",
  August: "August",
  September: "September",
  October: "October",
  November: "November",
  December: "December",
};
